### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by kdrcetintas** [Athlon1600/SerpScraper#21]
Hello,

I'm getting always recaptcha from google,
Do you have any specific parameter or option for get default image captcha or will come any update about recaptcha token solve function on dbc api ?

Thanks

**Comment by Athlon1600** [comment]
The problem is google moving  away from its image-based captchas which could be easily solved via DeathByCaptcha, to its new "I am not a robot" type captchas which is impossible for scripts to solve at the moment. I have no solution at this time, but this will be solved eventually.
