### ISSUE TITLE
call to undefined method GuzzleHttp\Psr7\Response::getEffectiveUrl()

### ISSUE THREAD

**Issue by abdulazizzulfikar** [Athlon1600/SerpScraper#24]
Call to undefined method GuzzleHttp\Psr7\Response::getEffectiveUrl() in C:\xampp\htdocs\latihan\crawl\vendor\athlon1600\serpscraper\src\Engine\GoogleSearch.php on line 147

**Comment by Athlon1600** [comment]
You must be using an outdated version of SerpScraper because Guzzle has been removed as a dependence over a year ago:  
https://github.com/Athlon1600/SerpScraper/commit/9d32d24dc70ec71042e4e1758682cb1661bc2f1d
