### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by feralheart** [Athlon1600/SerpScraper#25]
I tried to make bingsearch, based on the example, but I always got empty resultArray.

This is the JSONencoded `$response`:
`{"error":"","html":{},"has_next_page":false,"results":[]} `

**Comment by Athlon1600** [comment]
Paste your code, because the code from the example here seems to work just fine:  
https://github.com/Athlon1600/SerpScraper#extract-search-results-from-bing

**Comment by Athlon1600** [comment]
Fixed.
