### ISSUE TITLE
google is returning empty array

### ISSUE THREAD

**Issue by mmuhd** [Athlon1600/SerpScraper#29]
Hi, thank you for this amazing tool, I am trying to use it, the bing implementation is just fine, but using google always return zero results, empty array, please is there a way to rectify that? thanks.

**Comment by Athlon1600** [comment]
Seems to all work fine from my end?

Have you checked if there's maybe an error that you're getting? Because that would explain why you would be getting zero results. What is the output that you get from this?

```php
$google = new GoogleSearch();
$res = $google->search('google');
var_dump($res->results);
var_dump($res->error);
```

**Comment by mmuhd** [comment]
Hi @Athlon1600  Thank you for the quick reply. This is the result of the `var_dump:`

array(0) { } string(0) ""

**Comment by Athlon1600** [comment]
okay.. I can't replicate this from my end. One more thing you could try for me:
^ run that same code again, and just add this at the end:
```php
var_dump($res->html);
```

**Comment by mmuhd** [comment]
with var_dump($res->html);

the result is: 
string(0) ""

**Comment by Athlon1600** [comment]
okay... just pushed something through. Can you try downloading the latest `dev` version of SerpScraper:
```bash
composer require athlon1600/serpscraper dev-master
```

and rerun those lines again?

**Comment by mmuhd** [comment]
Woow thank you so much @Athlon1600 I have updated it and it is working perfectly. Thank you once again.
