### ISSUE TITLE
Notice: Undefined offset: -9 SearchEngine.php on line 116

### ISSUE THREAD

**Issue by fjhadz1** [Athlon1600/SerpScraper#4]
Hi,
Hope your doing great!

I'm currently new about this stuff and encountered problem on your script. Notice: Undefined offset: -9 SearchEngine.php on line 116. I'm not sure how to fix this problem and I would appreciate if you can help me with this.

Thanks!

**Comment by Athlon1600** [comment]
I can't seem to replicate this problem on my end. Have you changed anything inside SearchEngine.php?

**Comment by fjhadz1** [comment]
No I didn't change the SearchEngine.php. I already fixed the problem though by changing line 111 to $hash = substr($hash, 0, 7); . Thank you so much.
