### ISSUE TITLE
Any proxy Implementation?

### ISSUE THREAD

**Issue by fjhadz1** [Athlon1600/SerpScraper#5]
Hi,

I just want to ask if there's any proxy implementation about this project. I need to use proxies in searching, and quite not sure where would I add those. 

Thanks.

**Comment by Athlon1600** [comment]
Yes, there is:  

``` php
$google = new GoogleSearch();
$google->setProxy('123.456.789.123:8080');
$response = $google->search('query');
```

**Comment by fjhadz1** [comment]
Cool thanks for your reply. 

Using wamp as my localhost , I've encountered this error though.
-> Warning: file_put_contents(C:\WINDOWS\TEMP/...
-> Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to save file
-> RuntimeException: Unable to save file C:\WINDOWS\TEMP/

I'm gonna accept that i'm kinda beginner of this stuff. Sorry about the trouble.

**Comment by Athlon1600** [comment]
That's probably because you don't have permissions to write in that directory. You need to pick some other directory for that:  

``` php

$google = new GoogleSearch();
$google->setCookieDir("C:/my_cookie_dir/"); // or whatever
$google->setProxy('123.456.789.123:8080');
$response = $google->search('query');
```

**Comment by fjhadz1** [comment]
Hi, I already change the locotion but it seems that It seems that it is still having errors.
file_put_contents(F:/cookies/..)  failed to open stream: Invalid argument

**Comment by Athlon1600** [comment]
You're probably failing to escape slashes: http://stackoverflow.com/questions/2410354/failed-to-open-stream-invalid-argument

**Comment by fjhadz1** [comment]
Yes, I already did follow those but still i'm getting the same error. I'm quite not sure whats the problem.

**Comment by Athlon1600** [comment]
Post me the EXACT error with the EXACT code that you're using. Because otherwise I don't know what you're doing.

**Comment by fjhadz1** [comment]
Thanks for your reply Athlon. I already fixed the problem by updating the code with the new one. I assume that the old one have conflicts with my pc. Thanks for the update by the way.
